### PR TITLE
Dashboard, Create Todo Lists, Create Todo List Entries

### PR DESCRIPTION
**Pull request by DaleCS**
## How to test:
Login and go to /dashboard. It should allow you to add todo lists on the left, and entries on the right.

### CODE REVIEW

**Review by tienquocnguyen — COMMENTED** [review]
Validations for fields are needed to address the addition of empty objects. Other than that, it lgtm.

**Comment by DaleCS** [comment]
> 
> 
> Validations for fields are needed to address the addition of empty objects. Other than that, it lgtm.

Added

**Comment by skuchibotla** [comment]
Looks awesome!! I'm able to create a list and add to it easily :)

**Review by tienquocnguyen — APPROVED** [review]
I trust u.

**Pull request merged**
